### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by 1ka** [pchmn/MaterialChipsInput#1]
When using a DialogFragment (AppCompatDialogFragment) I see this crash when the layout is inflated.

If I get time, I might submit a fix and pull request, but have noted it here until then.

`Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity`
`  at com.pchmn.materialchips.ChipsInput.init(ChipsInput.java:144)`
`  at com.pchmn.materialchips.ChipsInput.<init>(ChipsInput.java:78)`
`  at java.lang.reflect.Constructor.newInstance0(Native Method) `

**Comment by pchmn** [comment]
Thanks for your return. I just fixed the bug and pushed the correction in v1.0.1 of the library. 

But there are still UI issues when using the library in DialogFragment. I'll look into it
