### ISSUE TITLE
How to customize text?

### ISSUE THREAD

**Issue by malkit89** [pchmn/MaterialChipsInput#37]
It's possibile to change the Chip textsize an typeface?
Thanks

**Comment by parthilystnow** [comment]
Im also looking for answers.. @malkit89  did u found any other way?

**Comment by malkit89** [comment]
After inflating chipview, you can find the textview inside it. Than you can set any parameter to textview. Here is the code example:
         ChipView **mChip** = (ChipView) findViewById(R.id.my_chip);
        TextView mLabel = (TextView) **mChip**.findViewById(**R.id.label**);
        mLabel.setTextSize(20);
