### ISSUE TITLE
Chip Click listener

### ISSUE THREAD

**Issue by Sese-Schneider** [pchmn/MaterialChipsInput#63]
Awesome library! I love it.

Is it somehow possible to add a onChipClickListener? 
if not, could you please add it in to your next release

Regards

**Comment by ivanchimeno** [comment]
@Sese-Schneider according to the README you can set a onClick listener to your chip:

```java
ChipView chip = (ChipView) findViewById(R.id.chip_view);
chip.setOnChipClicked(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        // handle click    
    }
});
````
