### ISSUE TITLE
Failed to resolve library

### ISSUE THREAD

**Issue by mstup** [pchmn/MaterialChipsInput#8]
For some reasons I got the following error message in Android Studio:
            Failed to resolve: com.github.pchmn:MaterialChipsInput:1.0.4
I used step-by-step instructions from here to reproduce the issue:
            https://github.com/pchmn/MaterialChipsInput

**Comment by chanmyaethu-mn** [comment]
Is there any ideas with 'failed to resolve'?

**Comment by chanmyaethu-mn** [comment]
I am OK by adding repo in project level gradle file and dependency to app level gradle file according to documentation.
Could you check it again with project level and app level gradle file @mstup ?
😄

**Comment by mstup** [comment]
As for me all looks like done in according to steps in document.
I just created new AndroidStudio project from scratch and got the same error.
My experiment in attach.
[ChipsTestApp.zip](https://github.com/pchmn/MaterialChipsInput/files/969719/ChipsTestApp.zip)

**Comment by chanmyaethu-mn** [comment]
@mstup 
Plz, try like this.
Project level gradle
buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()

        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

App Level Gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.mys.chipstestapp"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("MaterialChipsInput")) {
                details.useVersion '25.3.1'
            }
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.pchmn:MaterialChipsInput:1.0.4'
    testCompile 'junit:junit:4.12'
}

**Comment by mstup** [comment]
Great. I finally get it works for me.
I had mistake in my Grandle configuration.
Sorry,
