### ISSUE TITLE
Add new chip from UI

### ISSUE THREAD

**Issue by chanmyaethu-mn** [pchmn/MaterialChipsInput#9]
Hi,
Is there any feature to add new chip from UI?
Thanks!

**Comment by pchmn** [comment]
Hi. What do you mean when you say "from UI" ? If you want to add a chip manually from your activity or anything else, you can do it. It is explained in the readme, in this [part ](https://github.com/pchmn/MaterialChipsInput#add-and-remove-chips-manually)

**Comment by chanmyaethu-mn** [comment]
@pchmn 
I would like to do like gmail which I can add new chip from text box or select chip from filtered list.
Thanks!

**Comment by pchmn** [comment]
If you have a list, you can pass it to the `ChipsInput` like explained [here](https://github.com/pchmn/MaterialChipsInput#suggestions). Or see an [example](https://github.com/pchmn/MaterialChipsInput/blob/master/sample/src/main/java/com/pchmn/sample/materialchipsinput/ContactListActivity.java) from the sample app. The list will be filtered automatically when user will type, and a chip will be added when the user will select an element.

If you want to add chip from text box, you will have to create your text box, and manually add a chip when user clicks on the text box by using the [`addChip()`](https://github.com/pchmn/MaterialChipsInput#add-and-remove-chips-manually) method.

**Comment by chanmyaethu-mn** [comment]
Thanks!
